#@TYPE: Machine
#@NAME: CubieBoard2 HDMI
#@DESCRIPTION: Machine configuration for the CubieBoard2 with the HDMI test display target.

require ov-cubieboard2.inc

KERNEL_DEVICETREE = "ov-hdmi.dtb"

SHORT_OV_MACHINE= "CB2-HDMI"
