#@TYPE: Machine
#@NAME: RaspberryPi 4 Development Board (64bit)
#@DESCRIPTION: Machine configuration for the RaspberryPi 4 in 64 bits mode

require ov-raspberrypi4.inc
require conf/machine/include/arm/armv8a/tune-cortexa72.inc

RPI_KERNEL_DEVICETREE_OVERLAYS:append = " \
    overlays/ov-cm4-57-lvds.dtbo \
    overlays/max98357a.dtbo \
"

KBUILD_DEFCONFIG:ov-rpi4-64 ?= "bcm2711_defconfig"

SDIMG_KERNELIMAGE ?= "kernel8.img"

UBOOT_MACHINE = "rpi_arm64_config"

ARMSTUB ?= "armstub8-gic.bin"
