#@TYPE: Machine
#@NAME: RaspberryPi CM4 CH57 (64bit)
#@DESCRIPTION: Machine configuration for the CM4-based CH57 in 64-bit mode

require ov-rpi4-64.inc

RPI_KERNEL_DEVICETREE_OVERLAYS:append = " \
    overlays/ov-cm4-ch57.dtbo \
    overlays/max98357a.dtbo \
"

SHORT_OV_MACHINE= "CM4-CH57"