#@TYPE: Machine
#@NAME: RaspberryPi CM4 PQ70 (64bit)
#@DESCRIPTION: Machine configuration for the CM4-based PQ70 in 64-bit mode

require ov-rpi4-64.inc

RPI_KERNEL_DEVICETREE_OVERLAYS:append = " \
    overlays/ov-cm4-pq70.dtbo \
    overlays/max98357a.dtbo \
"

SHORT_OV_MACHINE= "CM4-PQ70"