#@TYPE: Machine
#@NAME: RaspberryPi 4 Development Board (64bit)
#@DESCRIPTION: Machine configuration for the RaspberryPi 4 in 64 bits mode

require ov-rpi4-64.inc

RPI_KERNEL_DEVICETREE_OVERLAYS:append = " \
    overlays/ov-rpi4-57-lvds.dtbo \
    overlays/max98357a.dtbo \
"

SHORT_OV_MACHINE= "RP4-64"