#@TYPE: Machine
#@NAME: Openvario with RaspberryPi 4 Board (32bit)
#@DESCRIPTION: Machine configuration for Openvario Hardare based on the RaspberryPi 4 in 32 bit mode

DEFAULTTUNE ?= "cortexa7thf-neon-vfpv4"

require ov-raspberrypi4.inc
require conf/machine/include/arm/armv7a/tune-cortexa7.inc

#RPI_KERNEL_DEVICETREE_OVERLAYS:append = " \
#    overlays/ov-rpi4-57-lvds.dtbo \
#"

KBUILD_DEFCONFIG:ov-rpi4 ?= "bcm2711_defconfig"

# 'l' stands for LPAE
SDIMG_KERNELIMAGE ?= "kernel7l.img"

UBOOT_MACHINE = "rpi_4_32b_config"

ARMSTUB ?= "armstub7.bin"
