#!/bin/sh

# reads rotation from cmdline convert it to degrees and writes

read -r cmdline < /proc/cmdline
for param in ${cmdline} ; do
  case "${param}" in
      fbcon=*)
          fbcon="${param#fbcon=}"
          ;;
  esac
done

case "${fbcon}" in
    "rotate:3")
        rotation=90
        ;;
    "rotate:2")
        rotation=180
        ;;
    "rotate:1")
        rotation=270
        ;;
    *)
        rotation=0
        ;;
esac
exec /usr/bin/psplash --angle "${rotation}"
