#!/bin/sh

# convert fbcon/rotate to degrees

case "$(sed -n 's/^rotation=//p' /boot/config.uEnv | tr -d '"')" in
	"3")
		rotation=90
		;;
	"2")
		rotation=180
		;;
	"1")
		rotation=270
		;;
	*)
		rotation=0
		;;
esac
exec /usr/bin/psplash --angle "${rotation}"
