# This is a basic workflow to verify incoming PRs with just one single machine (openvario-57-lvds)
name: verify_pr

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Verify_PR:
    
    name: Verify recipes at Pull Requests
    
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
                
      - name: Checkout sources
        uses: actions/checkout@v2
        
      - name: Update submodules
        run: git submodule update --init
      
      - name: Verify recipies
        env:
          MACHINE: openvario-57-lvds
        run: |
          docker run -v ${{ github.workspace }}:/workdir ghcr.io/openvario/ovbuild-container:main --workdir=/workdir source openembedded-core/oe-init-build-env . &&  bitbake openvario-image-testing --dry-run

